version: '3'
services:
  protractor:
    image: ccd-protractor:latest
    build:
      context: ./test
      dockerfile: DockerfileTests
    environment:
      - CCD_CASEWORKER_AUTOTEST_EMAIL
      - CCD_CASEWORKER_AUTOTEST_PASSWORD
      - TEST_URL
    volumes:
      - "$PWD:/protractor"
