nodejs:
  ingressHost: ${SERVICE_FQDN}
  image: ${IMAGE_NAME}
  applicationPort: 3451
  memoryRequests: 256Mi
  cpuRequests: 25m
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    CCD_GW_OAUTH2_CLIENT_ID: ccd_gateway
    CCD_PAGE_SIZE: 25
    CCD_ACTIVITY_NEXT_POLL_REQUEST_MS: 5000
    CCD_ACTIVITY_RETRY: 5
    CCD_ACTIVITY_BATCH_COLLECTION_DELAY_MS: 1
    CCD_ACTIVITY_MAX_REQUEST_PER_BATCH: 25

tags:
  - idam-pr
idam-pr:
  service:
    name: CCD # this is the label (name) of the service as configured in IDAM.
    redirect_uri: https://${SERVICE_FQDN}/oauth2redirect # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
